# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Zone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Zone.proto',
  package='Entities.Protobuf.Proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nZone.proto\x12\x17\x45ntities.Protobuf.Proto*$\n\x04Zone\x12\x07\n\x03RED\x10\x00\x12\x08\n\x04\x42LUE\x10\x01\x12\t\n\x05GREEN\x10\x02\x62\x06proto3')
)

_ZONE = _descriptor.EnumDescriptor(
  name='Zone',
  full_name='Entities.Protobuf.Proto.Zone',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GREEN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=39,
  serialized_end=75,
)
_sym_db.RegisterEnumDescriptor(_ZONE)

Zone = enum_type_wrapper.EnumTypeWrapper(_ZONE)
RED = 0
BLUE = 1
GREEN = 2


DESCRIPTOR.enum_types_by_name['Zone'] = _ZONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
