# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrderRecord.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Entities.GeneralOrderInformation_pb2 as GeneralOrderInformation__pb2
import Entities.Status_pb2 as Status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrderRecord.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11OrderRecord.proto\x1a\x1dGeneralOrderInformation.proto\x1a\x0cStatus.proto\"\xbb\x01\n\x0bOrderRecord\x12;\n\x19general_order_information\x18\x01 \x01(\x0b\x32\x18.GeneralOrderInformation\x12.\n\rstatuses_info\x18\x02 \x03(\x0b\x32\x17.OrderRecord.StatusInfo\x1a?\n\nStatusInfo\x12\x17\n\x06status\x18\x02 \x01(\x0e\x32\x07.Status\x12\x18\n\x10timestamp_millis\x18\x03 \x01(\x03\x62\x06proto3')
  ,
  dependencies=[GeneralOrderInformation__pb2.DESCRIPTOR,Status__pb2.DESCRIPTOR,])




_ORDERRECORD_STATUSINFO = _descriptor.Descriptor(
  name='StatusInfo',
  full_name='OrderRecord.StatusInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='OrderRecord.StatusInfo.status', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_millis', full_name='OrderRecord.StatusInfo.timestamp_millis', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=254,
)

_ORDERRECORD = _descriptor.Descriptor(
  name='OrderRecord',
  full_name='OrderRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='general_order_information', full_name='OrderRecord.general_order_information', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statuses_info', full_name='OrderRecord.statuses_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ORDERRECORD_STATUSINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=254,
)

_ORDERRECORD_STATUSINFO.fields_by_name['status'].enum_type = Status__pb2._STATUS
_ORDERRECORD_STATUSINFO.containing_type = _ORDERRECORD
_ORDERRECORD.fields_by_name['general_order_information'].message_type = GeneralOrderInformation__pb2._GENERALORDERINFORMATION
_ORDERRECORD.fields_by_name['statuses_info'].message_type = _ORDERRECORD_STATUSINFO
DESCRIPTOR.message_types_by_name['OrderRecord'] = _ORDERRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRecord = _reflection.GeneratedProtocolMessageType('OrderRecord', (_message.Message,), dict(

  StatusInfo = _reflection.GeneratedProtocolMessageType('StatusInfo', (_message.Message,), dict(
    DESCRIPTOR = _ORDERRECORD_STATUSINFO,
    __module__ = 'OrderRecord_pb2'
    # @@protoc_insertion_point(class_scope:OrderRecord.StatusInfo)
    ))
  ,
  DESCRIPTOR = _ORDERRECORD,
  __module__ = 'OrderRecord_pb2'
  # @@protoc_insertion_point(class_scope:OrderRecord)
  ))
_sym_db.RegisterMessage(OrderRecord)
_sym_db.RegisterMessage(OrderRecord.StatusInfo)


# @@protoc_insertion_point(module_scope)
