# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StatusSequence.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StatusSequence.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14StatusSequence.proto*>\n\x0eStatusSequence\x12\n\n\x06\x46ILLED\x10\x00\x12\x12\n\x0ePARTIAL_FILLED\x10\x01\x12\x0c\n\x08REJECTED\x10\x02\x62\x06proto3')
)

_STATUSSEQUENCE = _descriptor.EnumDescriptor(
  name='StatusSequence',
  full_name='StatusSequence',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FILLED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARTIAL_FILLED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REJECTED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=24,
  serialized_end=86,
)
_sym_db.RegisterEnumDescriptor(_STATUSSEQUENCE)

StatusSequence = enum_type_wrapper.EnumTypeWrapper(_STATUSSEQUENCE)
FILLED = 0
PARTIAL_FILLED = 1
REJECTED = 2


DESCRIPTOR.enum_types_by_name['StatusSequence'] = _STATUSSEQUENCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
